using System.Collections.Generic;
using System.Runtime.CompilerServices;

namespace Noesis.MonoGame;

internal static class KeyConverter
{
    private static readonly Dictionary<Microsoft.Xna.Framework.Input.Keys, Key> _noesisKeys = new()
        {
            { Microsoft.Xna.Framework.Input.Keys.Back, Key.Back },
            { Microsoft.Xna.Framework.Input.Keys.Tab, Key.Tab },
            { Microsoft.Xna.Framework.Input.Keys.Enter, Key.Enter },
            { Microsoft.Xna.Framework.Input.Keys.Pause, Key.Pause },
            { Microsoft.Xna.Framework.Input.Keys.CapsLock, Key.CapsLock },
            { Microsoft.Xna.Framework.Input.Keys.Kana, Key.KanaMode },
            { Microsoft.Xna.Framework.Input.Keys.Kanji, Key.KanjiMode },
            { Microsoft.Xna.Framework.Input.Keys.Escape, Key.Escape },
            { Microsoft.Xna.Framework.Input.Keys.ImeConvert, Key.ImeConvert },
            { Microsoft.Xna.Framework.Input.Keys.ImeNoConvert, Key.ImeNonConvert },
            { Microsoft.Xna.Framework.Input.Keys.Space, Key.Space },
            { Microsoft.Xna.Framework.Input.Keys.PageUp, Key.PageUp },
            { Microsoft.Xna.Framework.Input.Keys.PageDown, Key.PageDown },
            { Microsoft.Xna.Framework.Input.Keys.End, Key.End },
            { Microsoft.Xna.Framework.Input.Keys.Home, Key.Home },
            { Microsoft.Xna.Framework.Input.Keys.Left, Key.Left },
            { Microsoft.Xna.Framework.Input.Keys.Up, Key.Up },
            { Microsoft.Xna.Framework.Input.Keys.Right, Key.Right },
            { Microsoft.Xna.Framework.Input.Keys.Down, Key.Down },
            { Microsoft.Xna.Framework.Input.Keys.Select, Key.Select },
            { Microsoft.Xna.Framework.Input.Keys.Print, Key.Print },
            { Microsoft.Xna.Framework.Input.Keys.Execute, Key.Execute },
            { Microsoft.Xna.Framework.Input.Keys.PrintScreen, Key.PrintScreen },
            { Microsoft.Xna.Framework.Input.Keys.Insert, Key.Insert },
            { Microsoft.Xna.Framework.Input.Keys.Delete, Key.Delete },
            { Microsoft.Xna.Framework.Input.Keys.Help, Key.Help },
            { Microsoft.Xna.Framework.Input.Keys.D0, Key.D0 },
            { Microsoft.Xna.Framework.Input.Keys.D1, Key.D1 },
            { Microsoft.Xna.Framework.Input.Keys.D2, Key.D2 },
            { Microsoft.Xna.Framework.Input.Keys.D3, Key.D3 },
            { Microsoft.Xna.Framework.Input.Keys.D4, Key.D4 },
            { Microsoft.Xna.Framework.Input.Keys.D5, Key.D5 },
            { Microsoft.Xna.Framework.Input.Keys.D6, Key.D6 },
            { Microsoft.Xna.Framework.Input.Keys.D7, Key.D7 },
            { Microsoft.Xna.Framework.Input.Keys.D8, Key.D8 },
            { Microsoft.Xna.Framework.Input.Keys.D9, Key.D9 },
            { Microsoft.Xna.Framework.Input.Keys.A, Key.A },
            { Microsoft.Xna.Framework.Input.Keys.B, Key.B },
            { Microsoft.Xna.Framework.Input.Keys.C, Key.C },
            { Microsoft.Xna.Framework.Input.Keys.D, Key.D },
            { Microsoft.Xna.Framework.Input.Keys.E, Key.E },
            { Microsoft.Xna.Framework.Input.Keys.F, Key.F },
            { Microsoft.Xna.Framework.Input.Keys.G, Key.G },
            { Microsoft.Xna.Framework.Input.Keys.H, Key.H },
            { Microsoft.Xna.Framework.Input.Keys.I, Key.I },
            { Microsoft.Xna.Framework.Input.Keys.J, Key.J },
            { Microsoft.Xna.Framework.Input.Keys.K, Key.K },
            { Microsoft.Xna.Framework.Input.Keys.L, Key.L },
            { Microsoft.Xna.Framework.Input.Keys.M, Key.M },
            { Microsoft.Xna.Framework.Input.Keys.N, Key.N },
            { Microsoft.Xna.Framework.Input.Keys.O, Key.O },
            { Microsoft.Xna.Framework.Input.Keys.P, Key.P },
            { Microsoft.Xna.Framework.Input.Keys.Q, Key.Q },
            { Microsoft.Xna.Framework.Input.Keys.R, Key.R },
            { Microsoft.Xna.Framework.Input.Keys.S, Key.S },
            { Microsoft.Xna.Framework.Input.Keys.T, Key.T },
            { Microsoft.Xna.Framework.Input.Keys.U, Key.U },
            { Microsoft.Xna.Framework.Input.Keys.V, Key.V },
            { Microsoft.Xna.Framework.Input.Keys.W, Key.W },
            { Microsoft.Xna.Framework.Input.Keys.X, Key.X },
            { Microsoft.Xna.Framework.Input.Keys.Y, Key.Y },
            { Microsoft.Xna.Framework.Input.Keys.Z, Key.Z },
            { Microsoft.Xna.Framework.Input.Keys.LeftWindows, Key.LWin },
            { Microsoft.Xna.Framework.Input.Keys.RightWindows, Key.RWin },
            { Microsoft.Xna.Framework.Input.Keys.Apps, Key.Apps },
            { Microsoft.Xna.Framework.Input.Keys.Sleep, Key.Sleep },
            { Microsoft.Xna.Framework.Input.Keys.NumPad0, Key.NumPad0 },
            { Microsoft.Xna.Framework.Input.Keys.NumPad1, Key.NumPad1 },
            { Microsoft.Xna.Framework.Input.Keys.NumPad2, Key.NumPad2 },
            { Microsoft.Xna.Framework.Input.Keys.NumPad3, Key.NumPad3 },
            { Microsoft.Xna.Framework.Input.Keys.NumPad4, Key.NumPad4 },
            { Microsoft.Xna.Framework.Input.Keys.NumPad5, Key.NumPad5 },
            { Microsoft.Xna.Framework.Input.Keys.NumPad6, Key.NumPad6 },
            { Microsoft.Xna.Framework.Input.Keys.NumPad7, Key.NumPad7 },
            { Microsoft.Xna.Framework.Input.Keys.NumPad8, Key.NumPad8 },
            { Microsoft.Xna.Framework.Input.Keys.NumPad9, Key.NumPad9 },
            { Microsoft.Xna.Framework.Input.Keys.Multiply, Key.Multiply },
            { Microsoft.Xna.Framework.Input.Keys.Add, Key.Add },
            { Microsoft.Xna.Framework.Input.Keys.Separator, Key.Separator },
            { Microsoft.Xna.Framework.Input.Keys.Subtract, Key.Subtract },
            { Microsoft.Xna.Framework.Input.Keys.Decimal, Key.Decimal },
            { Microsoft.Xna.Framework.Input.Keys.Divide, Key.Divide },
            { Microsoft.Xna.Framework.Input.Keys.F1, Key.F1 },
            { Microsoft.Xna.Framework.Input.Keys.F2, Key.F2 },
            { Microsoft.Xna.Framework.Input.Keys.F3, Key.F3 },
            { Microsoft.Xna.Framework.Input.Keys.F4, Key.F4 },
            { Microsoft.Xna.Framework.Input.Keys.F5, Key.F5 },
            { Microsoft.Xna.Framework.Input.Keys.F6, Key.F6 },
            { Microsoft.Xna.Framework.Input.Keys.F7, Key.F7 },
            { Microsoft.Xna.Framework.Input.Keys.F8, Key.F8 },
            { Microsoft.Xna.Framework.Input.Keys.F9, Key.F9 },
            { Microsoft.Xna.Framework.Input.Keys.F10, Key.F10 },
            { Microsoft.Xna.Framework.Input.Keys.F11, Key.F11 },
            { Microsoft.Xna.Framework.Input.Keys.F12, Key.F12 },
            { Microsoft.Xna.Framework.Input.Keys.F13, Key.F13 },
            { Microsoft.Xna.Framework.Input.Keys.F14, Key.F14 },
            { Microsoft.Xna.Framework.Input.Keys.F15, Key.F15 },
            { Microsoft.Xna.Framework.Input.Keys.F16, Key.F16 },
            { Microsoft.Xna.Framework.Input.Keys.F17, Key.F17 },
            { Microsoft.Xna.Framework.Input.Keys.F18, Key.F18 },
            { Microsoft.Xna.Framework.Input.Keys.F19, Key.F19 },
            { Microsoft.Xna.Framework.Input.Keys.F20, Key.F20 },
            { Microsoft.Xna.Framework.Input.Keys.F21, Key.F21 },
            { Microsoft.Xna.Framework.Input.Keys.F22, Key.F22 },
            { Microsoft.Xna.Framework.Input.Keys.F23, Key.F23 },
            { Microsoft.Xna.Framework.Input.Keys.F24, Key.F24 },
            { Microsoft.Xna.Framework.Input.Keys.NumLock, Key.NumLock },
            { Microsoft.Xna.Framework.Input.Keys.Scroll, Key.Scroll },
            { Microsoft.Xna.Framework.Input.Keys.LeftShift, Key.LeftShift },
            { Microsoft.Xna.Framework.Input.Keys.RightShift, Key.RightShift },
            { Microsoft.Xna.Framework.Input.Keys.LeftControl, Key.LeftCtrl },
            { Microsoft.Xna.Framework.Input.Keys.RightControl, Key.RightCtrl },
            { Microsoft.Xna.Framework.Input.Keys.LeftAlt, Key.LeftAlt },
            { Microsoft.Xna.Framework.Input.Keys.RightAlt, Key.RightAlt },
            { Microsoft.Xna.Framework.Input.Keys.BrowserBack, Key.BrowserBack },
            { Microsoft.Xna.Framework.Input.Keys.BrowserForward, Key.BrowserForward },
            { Microsoft.Xna.Framework.Input.Keys.BrowserRefresh, Key.BrowserRefresh },
            { Microsoft.Xna.Framework.Input.Keys.BrowserStop, Key.BrowserStop },
            { Microsoft.Xna.Framework.Input.Keys.BrowserSearch, Key.BrowserSearch },
            { Microsoft.Xna.Framework.Input.Keys.BrowserFavorites, Key.BrowserFavorites },
            { Microsoft.Xna.Framework.Input.Keys.BrowserHome, Key.BrowserHome },
            { Microsoft.Xna.Framework.Input.Keys.VolumeMute, Key.VolumeMute },
            { Microsoft.Xna.Framework.Input.Keys.VolumeDown, Key.VolumeDown },
            { Microsoft.Xna.Framework.Input.Keys.VolumeUp, Key.VolumeUp },
            { Microsoft.Xna.Framework.Input.Keys.MediaNextTrack, Key.MediaNextTrack },
            { Microsoft.Xna.Framework.Input.Keys.MediaPreviousTrack, Key.MediaPreviousTrack },
            { Microsoft.Xna.Framework.Input.Keys.MediaStop, Key.MediaStop },
            { Microsoft.Xna.Framework.Input.Keys.MediaPlayPause, Key.MediaPlayPause },
            { Microsoft.Xna.Framework.Input.Keys.LaunchMail, Key.LaunchMail },
            { Microsoft.Xna.Framework.Input.Keys.SelectMedia, Key.SelectMedia },
            { Microsoft.Xna.Framework.Input.Keys.LaunchApplication1, Key.LaunchApplication1 },
            { Microsoft.Xna.Framework.Input.Keys.LaunchApplication2, Key.LaunchApplication2 },
            { Microsoft.Xna.Framework.Input.Keys.OemSemicolon, Key.OemSemicolon },
            { Microsoft.Xna.Framework.Input.Keys.OemPlus, Key.OemPlus },
            { Microsoft.Xna.Framework.Input.Keys.OemComma, Key.OemComma },
            { Microsoft.Xna.Framework.Input.Keys.OemMinus, Key.OemMinus },
            { Microsoft.Xna.Framework.Input.Keys.OemPeriod, Key.OemPeriod },
            { Microsoft.Xna.Framework.Input.Keys.OemQuestion, Key.OemQuestion },
            { Microsoft.Xna.Framework.Input.Keys.OemTilde, Key.OemTilde },           
            { Microsoft.Xna.Framework.Input.Keys.OemOpenBrackets, Key.OemOpenBrackets },
            { Microsoft.Xna.Framework.Input.Keys.OemPipe, Key.OemPipe },
            { Microsoft.Xna.Framework.Input.Keys.OemCloseBrackets, Key.OemCloseBrackets },
            { Microsoft.Xna.Framework.Input.Keys.OemQuotes, Key.OemQuotes },
            { Microsoft.Xna.Framework.Input.Keys.Oem8, Key.Oem8 },
            { Microsoft.Xna.Framework.Input.Keys.OemBackslash, Key.OemBackslash },
            { Microsoft.Xna.Framework.Input.Keys.ProcessKey, Key.ImeProcessed },
            { Microsoft.Xna.Framework.Input.Keys.OemCopy, Key.OemCopy },
            { Microsoft.Xna.Framework.Input.Keys.OemAuto, Key.OemAuto },
            { Microsoft.Xna.Framework.Input.Keys.OemEnlW, Key.OemEnlw },
            { Microsoft.Xna.Framework.Input.Keys.Attn, Key.Attn },
            { Microsoft.Xna.Framework.Input.Keys.Crsel, Key.CrSel },
            { Microsoft.Xna.Framework.Input.Keys.Exsel, Key.ExSel },
            { Microsoft.Xna.Framework.Input.Keys.EraseEof, Key.EraseEof },
            { Microsoft.Xna.Framework.Input.Keys.Play, Key.Play },
            { Microsoft.Xna.Framework.Input.Keys.Zoom, Key.Zoom },
            { Microsoft.Xna.Framework.Input.Keys.Pa1, Key.Pa1 },
            { Microsoft.Xna.Framework.Input.Keys.OemClear, Key.OemClear },
        };


    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Key Convert(Microsoft.Xna.Framework.Input.Keys key)
    {
        return _noesisKeys.TryGetValue(key, out Key result) ? result : Key.None;
    }
}